### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [ShivanshuKGupta/remote#1]
Thanks for putting your app in the open! Did you already decide what license it shall use? If not, [SPDX](https://spdx.org/licenses/) might help you. Ideally pick one that's approved by OSI/FSF as they are approved to be "libre".

**Comment by IzzySoft** [comment]
Any word, @ShivanshuKGupta?

**Comment by ShivanshuKGupta** [comment]
Hi @IzzySoft,
Sorry for the late reply, and thanks for considering to help me.
I have recently added a BSD 3-Clause License to the repo.

**Comment by ShivanshuKGupta** [comment]
I'm closing the issue as it is resolved now.

**Comment by IzzySoft** [comment]
Thanks for getting back to me! Just wondering: does this only work with a Windows PC, or also with Linux/Mac? And are there some screenshots available from the app?

**Comment by raman04-byte** [comment]
I have tested it on Mac and it's not working right now but in future this might work

**Comment by ShivanshuKGupta** [comment]
Hi @IzzySoft 
Currently, it only works with a Windows machine. But, we are working on expanding it to Mac and then we will move forward for Linux systems.

I will add some screenshots by tomorrow in the Readme

**Comment by IzzySoft** [comment]
Thanks for the updates, both of you! So once screenshots are available, I might see that I can add the app to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) if you like. To have the metadata always up-to-date, you could add the screenshots plus description here in the app's repo using Fastlane structures (be welcome using the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) for guidance). Should that look to overwhelming, just provide the screenshots and I'll send back a PR with a "fastlane starter package" you then can build upon, if you like; just let me know.

**Comment by ShivanshuKGupta** [comment]
Hi @IzzySoft,
I have added some screenshots in the repo.

**Comment by IzzySoft** [comment]
Thanks! Just went to add it, but discovered two things – one of them a show-stopper:

    Signer #1 certificate DN: C=US, O=Android, CN=Android Debug

You're using a debug key to sign the APK. Can you please sign it with a proper release key? And while speaking about signing:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

This can easily be avoided:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by ShivanshuKGupta** [comment]
I will look into the issues tomorrow.
Also, can you provide your LinkedIn profile, so we can talk there from now on?

**Comment by IzzySoft** [comment]
> I will look into the issues tomorrow.

Thanks!

> Also, can you provide your LinkedIn profile, so we can talk there from now on?

Nope, can't. I don't work with those proprietary "services" (so no Facebook, WhatsApp, Tiktok etc. either). You can find me on community-driven places, though – like on the Fediverse as [@IzzyOnDroid@floss.social](https://floss.social/@IzzyOnDroid) for example.
